<?php

namespace App\Messengers;

class SmsMessenger extends AbstractMessenger
{

    public function send(): bool
    {
        \info("Sent by" . __METHOD__);
        return parent::send(); // TODO: Change the autogenerated stub
    }
}
